### ISSUE TITLE
Kerbal Spaceship node not displayed

### ISSUE THREAD

**Issue by SamHillcoat** [hudsonfoo/kerbal-openmct#5]
When Open MCT starts, the Kerbal spacecraft node is not displayed, I am unsure if I have installed the plugin correctly. I have this repository cloned into ~openmct\example\kerbal (this is where the bundle.js file is located), and the Main.js file has been edited to include the kerbal bundle.

Why am I not seeing the Kerbal Spacecraft node? Any help would be appreciated.

**Comment by hudsonfoo** [comment]
Open the developers console of your browser and see if there are any errors. If so, please post them here.

**Comment by SamHillcoat** [comment]
Seems to be somthing with angular js.

`Error: [ng:areq] http://errors.angularjs.org/1.4.4/ng/areq?p0=InspectorController&p1=not%20aNaNunction%2C%20got%20undefined
    at Error (native)
    at http://localhost:8080/bower_components/angular/angular.min.js:6:416
    at pb (http://localhost:8080/bower_components/angular/angular.min.js:22:41)
    at Sa (http://localhost:8080/bower_components/angular/angular.min.js:22:128)
    at http://localhost:8080/bower_components/angular/angular.min.js:80:25
    at N (http://localhost:8080/bower_components/angular/angular.min.js:59:447)
    at K (http://localhost:8080/bower_components/angular/angular.min.js:60:287)
    at g (http://localhost:8080/bower_components/angular/angular.min.js:54:326)
    at http://localhost:8080/bower_components/angular/angular.min.js:53:388
    at populateElement (http://localhost:8080/platform/representation/src/TemplateLinker.js:125:50)
Error: [ng:areq] http://errors.angularjs.org/1.4.4/ng/areq?p0=InspectorController&p1=not%20a%20function%2C%20got%20undefined
    at Error (native)
    at http://localhost:8080/bower_components/angular/angular.min.js:6:416
    at pb (http://localhost:8080/bower_components/angular/angular.min.js:22:41)
    at Sa (http://localhost:8080/bower_components/angular/angular.min.js:22:128)
    at http://localhost:8080/bower_components/angular/angular.min.js:80:25
    at N (http://localhost:8080/bower_components/angular/angular.min.js:59:447)
    at K (http://localhost:8080/bower_components/angular/angular.min.js:60:287)
    at g (http://localhost:8080/bower_components/angular/angular.min.js:54:326)
    at http://localhost:8080/bower_components/angular/angular.min.js:53:388
    at populateElement (http://localhost:8080/platform/representation/src/TemplateLinker.js:125:50)
`

**Comment by hudsonfoo** [comment]
Sounds like you may not have Open MCT set up correctly. Possibly missing dependencies. I just did a fresh clone of Open MCT and a fresh clone of this repo, followed the steps and everything works.

**Comment by SamHillcoat** [comment]
Ok then, I'll give that a go. Thanks for the help.

**Comment by SamHillcoat** [comment]
Ok, got it working. It seems my version of node.js was outdated.
